### ISSUE TITLE
Create updated HMDA data sets

### ISSUE THREAD

**Issue by ptatian** [NeighborhoodInfoDC/HMDA#6]

**Comment by ptatian** [comment]
@rpitingolo Here are links to the documents that list the HMDA-based indicators that we need for the products in development.
- https://urbanorg.box.com/s/lzhwl2pspf4lzb681yuqzq1zxpbz0nli
- https://urbanorg.box.com/s/of7v935e3jaspmuk7lyqtwjo079aebnj

Should do issue #3 first.

**Comment by rpitingolo** [comment]
@ptatian I've got this pretty close, but there's one thing I'm unsure about... do we still want to create the subprime_lender indicator on the base file? If so, I'm not able to do it because to do it requires a format which requires the dataset Hmda.Lenders_&year. to create, and that doesn't appear to exist on L. Let me know what you think.

**Comment by ptatian** [comment]
@rpitingolo I don't think the subprime lender indicator is relevant anymore. [We were relying on HUD](https://www.huduser.gov/portal/datasets/manu.html) for that classification and they seem to have stopped doing it. cc: @lhendey

**Comment by rpitingolo** [comment]
@ptatian thanks. I'm going to leave it off of the base file then. @lhendey

**Comment by ptatian** [comment]
@rpitingolo Sounds good. We should keep the older subprime data. You are just talking about the new data, correct?

**Comment by rpitingolo** [comment]
@ptatian yes, correct.

**Comment by rpitingolo** [comment]
@ptatian an issue I'm running into is that some records are missing tract IDs on the raw data. It appears to be more in the earlier years but I'm trying to diagnose how bad it is and then will see if I can come up with a proposed idea for it.
